"""Baseline: the full pre-Alembic schema (autogenerated from models.py).

Legacy databases created by ``Base.metadata.create_all`` are stamped with
this revision instead of running it (see ``app.migrations.run_migrations``).

Revision ID: 0001
Revises:
Create Date: 2026-07-15 00:09:33.331888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.String(length=100), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('current_odometer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_user_id'), ['user_id'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_type'), ['type'], unique=False)

    op.create_table('service_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_odometer', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('last_notified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_intervals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_intervals_car_id'), ['car_id'], unique=False)

    op.create_table('maintenance_details',
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_entry_id')
    )
    op.create_table('refuel_details',
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_full_tank', sa.Boolean(), nullable=False),
    sa.Column('gas_station', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_entry_id')
    )
    op.create_table('repair_details',
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('warranty_km', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_entry_id')
    )


def downgrade() -> None:
    op.drop_table('repair_details')
    op.drop_table('refuel_details')
    op.drop_table('maintenance_details')
    with op.batch_alter_table('service_intervals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_intervals_car_id'))

    op.drop_table('service_intervals')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_type'))
        batch_op.drop_index(batch_op.f('ix_log_entries_date'))
        batch_op.drop_index(batch_op.f('ix_log_entries_car_id'))

    op.drop_table('log_entries')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_user_id'))

    op.drop_table('cars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
